### ISSUE TITLE
concept_vectors.npy

### ISSUE THREAD

**Issue by suharabbani** [lenbrocki/concept-saliency-maps#2]
Hi,

How can I create the concept_vectors.npy file which is being used in the Dot products and histograms section?

**Comment by lenbrocki** [comment]
Hi,

the numpy array concept_vectors, which is created in the previous section Obtain concept vectors, is the one loaded in the line you are referring to.
Therefore you can either put in a line 
`np.save('concept_vectors.npy', concept_vectors.npy)`
right after this array is created.
Or just delete the line where the file concept_vectors.npy is loaded and work directly with the array.

Thank you for pointing this out, I will change the notebook accordingly.

**Comment by suharabbani** [comment]
Thanks!
